sudo: required
services:
  - docker

before_install:
  - docker build -t sawoohoorun/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true sawoohoorun/react-test npm test

after_success:
  - docker build -t sawoohoorun/multi-client ./client
  - docker build -t sawoohoorun/multi-nginx ./nginx
  - docker build -t sawoohoorun/multi-server ./server
  - docker build -t sawoohoorun/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Tack those images and push them to docker hub

  - docker push sawoohoorun/multi-client
  - docker push sawoohoorun/multi-nginx
  - docker push sawoohoorun/multi-server
  - docker push sawoohoorun/multi-worker
